import { useEffect, useState, useRef, useCallback } from 'react';
import { fetchSummary } from '@/lib/api';
import { SUB_PERSONA_REGISTRY } from '@/types/modules';
import type { SubPersonaId } from '@/types/modules';
import { Skeleton } from '@/components/ui/skeleton';
import { Card } from '@/components/ui/card';
import { AlertCircle } from 'lucide-react';
import PersonaSelector from './PersonaSelector';

interface SummaryContent {
  narrative_summary: string;
  disclaimer?: string;
  // backward compat
  summary_points?: string[];
}

interface PersonalizedSummaryCardProps {
  paperId: number;
  subPersonaId: SubPersonaId;
  onPersonaChange: (id: SubPersonaId) => void;
  allowedPersonas?: SubPersonaId[];
}

const PersonalizedSummaryCard = ({ paperId, subPersonaId, onPersonaChange, allowedPersonas }: PersonalizedSummaryCardProps) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);
  const [content, setContent] = useState<SummaryContent | null>(null);
  const cacheRef = useRef<Record<string, SummaryContent>>({});

  const loadSummary = useCallback(async () => {
    if (cacheRef.current[subPersonaId]) {
      setContent(cacheRef.current[subPersonaId]);
      setError(false);
      return;
    }

    setLoading(true);
    setError(false);
    try {
      const data = await fetchSummary(paperId, subPersonaId);
      const summaryContent = (data?.content ?? data) as SummaryContent;
      cacheRef.current[subPersonaId] = summaryContent;
      setContent(summaryContent);
    } catch {
      setError(true);
      setContent(null);
    } finally {
      setLoading(false);
    }
  }, [paperId, subPersonaId]);

  useEffect(() => {
    loadSummary();
  }, [loadSummary]);

  /** Turn "(p. 12)" references into styled spans */
  const renderWithPageRefs = (text: string) => {
    const parts = text.split(/(\(p\.\s*\d+(?:\s*[-–,]\s*\d+)*\))/g);
    return parts.map((part, i) =>
      /^\(p\./.test(part) ? (
        <span key={i} className="text-primary font-medium cursor-pointer hover:underline">
          {part}
        </span>
      ) : (
        <span key={i}>{part}</span>
      ),
    );
  };

  const getNarrative = (c: SummaryContent): string => {
    if (c.narrative_summary) return c.narrative_summary;
    // backward compat: join old bullet points
    if (c.summary_points) return c.summary_points.join(' ');
    return '';
  };

  return (
    <Card className="relative overflow-hidden border-l-4 border-l-primary shadow-sm rounded-xl">
      {/* Header row */}
      <div className="flex items-center justify-between p-5 pb-3">
        <h2 className="font-sans text-xl font-semibold text-foreground">
          Personalized Summary
        </h2>
        <PersonaSelector value={subPersonaId} onChange={onPersonaChange} allowedPersonas={allowedPersonas} />
      </div>

      <div className="px-5 pb-5">
        {loading && (
          <div className="space-y-3">
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-5/6" />
            <Skeleton className="h-4 w-4/6" />
            <Skeleton className="h-4 w-full" />
          </div>
        )}

        {!loading && error && (
          <div className="flex items-center gap-2 text-muted-foreground text-sm">
            <AlertCircle className="h-4 w-4 shrink-0" />
            <p>Summary generation in progress. Please try again in a moment.</p>
          </div>
        )}

        {!loading && content && (
          <>
            <p className="text-base text-foreground/90 leading-relaxed">
              {renderWithPageRefs(getNarrative(content))}
            </p>
            <p className="mt-3 text-xs italic text-muted-foreground">
              {content.disclaimer || "⚠️ This summary was generated by AI and may contain inaccuracies. Always refer to the original paper for definitive information."}
            </p>
          </>
        )}
      </div>
    </Card>
  );
};

export default PersonalizedSummaryCard;
